# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowmies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('ride_with', models.CharField(max_length=255)),
                ('experience_lvl', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('ride_type', models.CharField(max_length=255)),
                ('more', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='snowmies.User')),
            ],
        ),
    ]
