# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowmies', '0002_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
